{% set name = "PyDTMC" %}
{% set version = "6.11.0" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5f3e9d6510d822d55f0ae828c4bd35a0eb9f8babd1e7f46d28e818fa2f00949

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - matplotlib-base
    - networkx
    - numpy
    - scipy

test:
  imports:
    - {{ name.lower() }}
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home: https://github.com/TommasoBelluzzo/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A framework for discrete-time Markov chains analysis.
  description: PyDTMC is a full-featured, lightweight library for discrete-time Markov chains analysis. It provides classes and functions for creating, manipulating, simulating and visualizing markovian stochastic processes.
  doc_url: https://{{ name.lower() }}.readthedocs.io/
  doc_source_url: https://github.com/TommasoBelluzzo/{{ name }}/blob/master/docs/source/index.rst
  dev_url: https://github.com/TommasoBelluzzo/{{ name }}

extra:
  recipe-maintainers:
    - TommasoBelluzzo
